discriminator:
  channels: 3
  num_features: 64
  num_residuals: 9
  depth: 5
  noise_std: 0.05
  dropout: 0.2
generator:
  channels: 3
  num_features: 64
  num_residuals: 9
  depth: 4
gan:
  # lambda_cycle: 10
  lambda_l1: 100
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  gen_wd: 0.05
  disc_wd: 0.1
