spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magicaldrones_dev
    username: ${MD_DB_USERNAME}
    password: ${MD_DB_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
