spring:
  application:
    name: magical-drones-webapp
  main:
    banner-mode: off

  profiles:
    active: prod

aws:
  region: us-east-1
  s3:
    bucket: magical-drones
    bucket-test: magical-drones-integration-tests

